START var=node(*),var=node(*) RETURN *;
START var=node:Label(prop="string") RETURN *;
START var=node:Label(prop={param}) RETURN *;
START var=node:Label("string") RETURN *;
START var=node:Label({param}) RETURN *;
START var=node(1) RETURN *;
START var=node(1, 2) RETURN *;
START var=node({param}) RETURN *;
START var=node(*) RETURN *;
START var=rel:Label(prop="string") RETURN *;
START var=rel:Label(prop={param}) RETURN *;
START var=rel:Label("string") RETURN *;
START var=rel:Label({param}) RETURN *;
START var=rel(1) RETURN *;
START var=rel(1, 2) RETURN *;
START var=rel({param}) RETURN *;
START var=rel(*) RETURN *;
START var=relationship:Label(prop="string") RETURN *;
START var=relationship:Label(prop={param}) RETURN *;
START var=relationship:Label("string") RETURN *;
START var=relationship:Label({param}) RETURN *;
START var=relationship(1) RETURN *;
START var=relationship(1, 2) RETURN *;
START var=relationship({param}) RETURN *;
START var=relationship(*) RETURN *;
