/* The following code was generated by JFlex 1.4.3 on 5/14/16 12:27 PM */

package com.neueda.jetbrains.plugin.cypher.lexer;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.neueda.jetbrains.plugin.cypher.psi.CypherTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/14/16 12:27 PM from the specification file
 * <tt>/Users/fylmtm/workspace/neueda4j/jetbrains-plugin-cypher/src/main/java/com/neueda4j/intellij/plugin/cypher/lexer/_CypherLexer.flex</tt>
 */
public class _CypherLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\2\1\0\1\1\1\1\22\0\1\1\1\66\1\44"+
    "\1\0\1\34\1\67\1\0\1\42\1\50\1\51\1\46\1\62\1\63"+
    "\1\37\1\41\1\45\1\35\11\40\1\56\1\47\1\60\1\57\1\61"+
    "\1\64\1\0\1\4\1\31\1\6\1\14\1\11\1\23\1\27\1\7"+
    "\1\15\1\30\1\33\1\20\1\3\1\13\1\17\1\26\1\24\1\10"+
    "\1\16\1\5\1\12\1\21\1\22\1\25\1\32\1\34\1\54\1\43"+
    "\1\55\1\70\1\34\1\36\1\4\1\31\1\6\1\14\1\11\1\23"+
    "\1\27\1\7\1\15\1\30\1\33\1\20\1\3\1\13\1\17\1\26"+
    "\1\24\1\10\1\16\1\5\1\12\1\21\1\22\1\25\1\32\1\34"+
    "\1\52\1\65\1\53\1\71\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\26\3\1\4\1\5\1\6\1\4"+
    "\1\7\2\1\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\1\1\31\1\32\3\3\1\33"+
    "\24\3\1\34\1\35\6\3\1\36\1\37\16\3\1\40"+
    "\1\3\2\0\1\41\1\0\1\42\3\0\1\43\1\0"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\2\3\1\52"+
    "\1\53\1\54\1\3\1\55\5\3\1\56\7\3\1\57"+
    "\1\60\10\3\1\61\13\3\1\62\15\3\1\63\5\3"+
    "\1\64\1\65\1\0\5\3\1\66\1\67\1\70\1\71"+
    "\12\3\1\72\1\73\7\3\1\74\1\75\1\76\1\77"+
    "\1\3\1\100\4\3\1\101\2\3\1\102\3\3\1\103"+
    "\1\3\1\104\1\105\1\3\1\106\5\3\1\107\2\3"+
    "\1\110\1\111\1\112\20\3\1\113\2\3\1\114\4\3"+
    "\1\115\1\116\2\3\1\117\1\3\1\120\1\121\1\122"+
    "\5\3\1\123\1\124\1\3\1\125\1\3\1\126\1\127"+
    "\2\3\1\130\1\3\1\131\1\132\1\133\2\3\1\134"+
    "\1\3\1\135\1\136\1\137\1\3\1\140\1\3\1\141"+
    "\1\3\1\142\2\3\1\143\7\3\1\144\1\3\1\145"+
    "\1\146\5\3\1\147\1\150\3\3\1\151\3\3\1\152"+
    "\1\3\1\153\1\3\1\154\1\155\7\3\1\156\1\3"+
    "\1\157\7\3\1\160\1\161\6\3\1\162\1\163";

  private static int [] zzUnpackAction() {
    int [] result = new int[371];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\u0196"+
    "\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366"+
    "\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536"+
    "\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658\0\u0692\0\u06cc\0\u0706"+
    "\0\u0740\0\72\0\72\0\72\0\72\0\72\0\72\0\72"+
    "\0\72\0\72\0\u077a\0\u07b4\0\u07ee\0\u0828\0\72\0\72"+
    "\0\72\0\u0862\0\72\0\72\0\u089c\0\u08d6\0\u0910\0\u094a"+
    "\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a"+
    "\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c\0\u0c76\0\u0cb0\0\u0cea"+
    "\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c\0\u03da\0\u0e46\0\u0e80"+
    "\0\u0eba\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2\0\u03da\0\u0fdc\0\u1016"+
    "\0\u1050\0\u108a\0\u10c4\0\u10fe\0\u1138\0\u1172\0\u11ac\0\u11e6"+
    "\0\u1220\0\u125a\0\u1294\0\u12ce\0\u03da\0\u1308\0\u1342\0\u137c"+
    "\0\72\0\u06cc\0\72\0\u13b6\0\u0706\0\u13f0\0\u142a\0\u1464"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\u149e\0\u14d8"+
    "\0\u03da\0\u03da\0\u1512\0\u154c\0\u1586\0\u15c0\0\u15fa\0\u1634"+
    "\0\u166e\0\u16a8\0\u03da\0\u16e2\0\u171c\0\u1756\0\u1790\0\u17ca"+
    "\0\u1804\0\u183e\0\u1878\0\u18b2\0\u18ec\0\u1926\0\u1960\0\u199a"+
    "\0\u19d4\0\u1a0e\0\u1a48\0\u1a82\0\u03da\0\u1abc\0\u1af6\0\u1b30"+
    "\0\u1b6a\0\u1ba4\0\u1bde\0\u1c18\0\u1c52\0\u1c8c\0\u1cc6\0\u1d00"+
    "\0\u03da\0\u1d3a\0\u1d74\0\u1dae\0\u1de8\0\u1e22\0\u1e5c\0\u1e96"+
    "\0\u1ed0\0\u1f0a\0\u1f44\0\u1f7e\0\u1fb8\0\u1ff2\0\u03da\0\u202c"+
    "\0\u2066\0\u20a0\0\u20da\0\u2114\0\u1342\0\72\0\u214e\0\u2188"+
    "\0\u21c2\0\u21fc\0\u2236\0\u2270\0\u03da\0\u03da\0\u03da\0\u03da"+
    "\0\u22aa\0\u22e4\0\u231e\0\u2358\0\u2392\0\u23cc\0\u2406\0\u2440"+
    "\0\u247a\0\u24b4\0\u03da\0\u03da\0\u24ee\0\u2528\0\u2562\0\u259c"+
    "\0\u25d6\0\u2610\0\u264a\0\u03da\0\u03da\0\u03da\0\u03da\0\u2684"+
    "\0\u26be\0\u26f8\0\u2732\0\u276c\0\u27a6\0\u03da\0\u27e0\0\u281a"+
    "\0\u03da\0\u2854\0\u288e\0\u28c8\0\u03da\0\u2902\0\u03da\0\u03da"+
    "\0\u293c\0\u03da\0\u2976\0\u29b0\0\u29ea\0\u2a24\0\u2a5e\0\u03da"+
    "\0\u2a98\0\u2ad2\0\u1464\0\u03da\0\u03da\0\u2b0c\0\u2b46\0\u2b80"+
    "\0\u2bba\0\u2bf4\0\u2c2e\0\u2c68\0\u2ca2\0\u2cdc\0\u2d16\0\u2d50"+
    "\0\u2d8a\0\u2dc4\0\u2dfe\0\u2e38\0\u2e72\0\u03da\0\u2eac\0\u2ee6"+
    "\0\u03da\0\u2f20\0\u2f5a\0\u2f94\0\u2fce\0\u03da\0\u3008\0\u3042"+
    "\0\u307c\0\u03da\0\u30b6\0\u03da\0\u03da\0\u03da\0\u30f0\0\u312a"+
    "\0\u3164\0\u319e\0\u31d8\0\u03da\0\u03da\0\u3212\0\u03da\0\u324c"+
    "\0\u03da\0\u03da\0\u3286\0\u32c0\0\u03da\0\u32fa\0\u03da\0\u03da"+
    "\0\u03da\0\u3334\0\u336e\0\u03da\0\u33a8\0\u03da\0\u03da\0\u03da"+
    "\0\u33e2\0\u03da\0\u341c\0\u03da\0\u3456\0\u03da\0\u3490\0\u34ca"+
    "\0\u03da\0\u3504\0\u353e\0\u3578\0\u35b2\0\u35ec\0\u3626\0\u3660"+
    "\0\u03da\0\u369a\0\u03da\0\u03da\0\u36d4\0\u370e\0\u3748\0\u3782"+
    "\0\u37bc\0\u03da\0\u03da\0\u37f6\0\u3830\0\u386a\0\u03da\0\u38a4"+
    "\0\u38de\0\u3918\0\u03da\0\u3952\0\u03da\0\u398c\0\u03da\0\u03da"+
    "\0\u39c6\0\u3a00\0\u3a3a\0\u3a74\0\u3aae\0\u3ae8\0\u3b22\0\u03da"+
    "\0\u3b5c\0\u03da\0\u3b96\0\u3bd0\0\u3c0a\0\u3c44\0\u3c7e\0\u3cb8"+
    "\0\u3cf2\0\u03da\0\u03da\0\u3d2c\0\u3d66\0\u3da0\0\u3dda\0\u3e14"+
    "\0\u3e4e\0\u03da\0\u03da";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[371];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\22\1\25\1\26\1\22\1\27"+
    "\1\30\1\31\2\22\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\2\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\2"+
    "\73\0\2\3\72\0\1\22\1\65\4\22\1\66\24\22"+
    "\2\0\1\22\34\0\10\22\1\67\2\22\1\70\1\22"+
    "\1\71\15\22\2\0\1\22\34\0\4\22\1\72\1\73"+
    "\25\22\2\0\1\22\34\0\1\22\1\74\3\22\1\75"+
    "\5\22\1\76\1\77\12\22\1\100\3\22\2\0\1\22"+
    "\34\0\6\22\1\101\24\22\2\0\1\22\34\0\6\22"+
    "\1\102\24\22\2\0\1\22\34\0\10\22\1\103\4\22"+
    "\1\104\4\22\1\105\10\22\2\0\1\22\34\0\10\22"+
    "\1\106\2\22\1\107\17\22\2\0\1\22\34\0\7\22"+
    "\1\110\4\22\1\111\16\22\2\0\1\22\34\0\5\22"+
    "\1\112\1\113\3\22\1\114\20\22\2\0\1\22\34\0"+
    "\10\22\1\115\2\22\1\116\17\22\2\0\1\22\34\0"+
    "\2\22\1\117\1\120\1\121\1\22\1\122\3\22\1\123"+
    "\15\22\1\124\2\22\2\0\1\22\34\0\5\22\1\125"+
    "\2\22\1\126\12\22\1\127\7\22\2\0\1\22\34\0"+
    "\12\22\1\130\1\22\1\131\16\22\2\0\1\22\34\0"+
    "\33\22\2\0\1\22\34\0\4\22\1\132\5\22\1\133"+
    "\20\22\2\0\1\22\34\0\1\22\1\134\3\22\1\135"+
    "\4\22\1\136\1\22\1\137\16\22\2\0\1\22\34\0"+
    "\14\22\1\140\16\22\2\0\1\22\34\0\5\22\1\141"+
    "\1\142\24\22\2\0\1\22\34\0\14\22\1\143\16\22"+
    "\2\0\1\22\34\0\6\22\1\144\20\22\1\145\3\22"+
    "\2\0\1\22\34\0\12\22\1\146\20\22\2\0\1\22"+
    "\72\0\1\147\30\0\36\150\1\0\33\150\35\0\1\32"+
    "\2\0\1\35\66\0\1\35\2\0\1\35\1\147\71\0"+
    "\1\151\30\0\42\152\1\153\1\154\26\152\43\155\1\156"+
    "\1\153\25\155\45\0\1\157\1\160\114\0\1\161\57\0"+
    "\1\162\1\0\1\163\67\0\1\164\47\0\1\32\2\0"+
    "\1\35\16\0\1\165\71\0\1\166\15\0\2\22\1\167"+
    "\30\22\2\0\1\22\34\0\5\22\1\170\25\22\2\0"+
    "\1\22\34\0\11\22\1\171\15\22\1\172\3\22\2\0"+
    "\1\22\34\0\3\22\1\173\7\22\1\174\17\22\2\0"+
    "\1\22\34\0\15\22\1\175\15\22\2\0\1\22\34\0"+
    "\6\22\1\176\24\22\2\0\1\22\34\0\7\22\1\177"+
    "\23\22\2\0\1\22\34\0\13\22\1\200\1\22\1\201"+
    "\15\22\2\0\1\22\34\0\6\22\1\202\24\22\2\0"+
    "\1\22\34\0\16\22\1\203\14\22\2\0\1\22\34\0"+
    "\1\204\7\22\1\205\22\22\2\0\1\22\34\0\23\22"+
    "\1\206\7\22\2\0\1\22\34\0\1\22\1\207\31\22"+
    "\2\0\1\22\34\0\1\210\1\22\1\211\6\22\1\212"+
    "\3\22\1\213\15\22\2\0\1\22\34\0\11\22\1\214"+
    "\21\22\2\0\1\22\34\0\13\22\1\215\17\22\2\0"+
    "\1\22\34\0\2\22\1\216\7\22\1\217\10\22\1\220"+
    "\7\22\2\0\1\22\34\0\12\22\1\221\4\22\1\222"+
    "\13\22\2\0\1\22\34\0\12\22\1\223\20\22\2\0"+
    "\1\22\34\0\15\22\1\224\15\22\2\0\1\22\34\0"+
    "\2\22\1\225\5\22\1\226\1\227\21\22\2\0\1\22"+
    "\34\0\14\22\1\230\16\22\2\0\1\22\34\0\2\22"+
    "\1\231\10\22\1\232\1\22\1\233\15\22\2\0\1\22"+
    "\34\0\13\22\1\234\17\22\2\0\1\22\34\0\11\22"+
    "\1\235\21\22\2\0\1\22\34\0\1\22\1\236\31\22"+
    "\2\0\1\22\34\0\1\22\1\237\31\22\2\0\1\22"+
    "\34\0\14\22\1\240\16\22\2\0\1\22\34\0\2\22"+
    "\1\241\30\22\2\0\1\22\34\0\10\22\1\242\22\22"+
    "\2\0\1\22\34\0\12\22\1\243\20\22\2\0\1\22"+
    "\34\0\11\22\1\244\21\22\2\0\1\22\34\0\2\22"+
    "\1\245\30\22\2\0\1\22\34\0\1\246\32\22\2\0"+
    "\1\22\34\0\1\22\1\247\31\22\2\0\1\22\34\0"+
    "\6\22\1\250\24\22\2\0\1\22\34\0\2\22\1\251"+
    "\30\22\2\0\1\22\34\0\15\22\1\252\15\22\2\0"+
    "\1\22\34\0\14\22\1\253\16\22\2\0\1\22\34\0"+
    "\6\22\1\254\6\22\1\255\15\22\2\0\1\22\34\0"+
    "\5\22\1\256\25\22\2\0\1\22\34\0\5\22\1\257"+
    "\25\22\2\0\1\22\34\0\14\22\1\260\16\22\2\0"+
    "\1\22\34\0\5\22\1\261\25\22\2\0\1\22\34\0"+
    "\12\22\1\262\20\22\2\0\1\22\34\0\24\22\1\263"+
    "\6\22\2\0\1\22\34\0\6\22\1\264\24\22\2\0"+
    "\1\22\66\0\1\265\2\0\1\265\31\0\36\150\1\266"+
    "\33\150\2\152\1\0\67\152\2\155\1\0\67\155\2\157"+
    "\1\0\67\157\46\160\1\267\23\160\3\0\3\22\1\270"+
    "\27\22\2\0\1\22\34\0\24\22\1\271\6\22\2\0"+
    "\1\22\34\0\6\22\1\272\24\22\2\0\1\22\34\0"+
    "\6\22\1\273\24\22\2\0\1\22\34\0\13\22\1\274"+
    "\17\22\2\0\1\22\34\0\10\22\1\275\22\22\2\0"+
    "\1\22\34\0\6\22\1\276\24\22\2\0\1\22\34\0"+
    "\6\22\1\277\24\22\2\0\1\22\34\0\15\22\1\300"+
    "\15\22\2\0\1\22\34\0\1\22\1\301\31\22\2\0"+
    "\1\22\34\0\1\302\32\22\2\0\1\22\34\0\2\22"+
    "\1\303\10\22\1\304\17\22\2\0\1\22\34\0\4\22"+
    "\1\305\26\22\2\0\1\22\34\0\11\22\1\306\21\22"+
    "\2\0\1\22\34\0\14\22\1\307\16\22\2\0\1\22"+
    "\34\0\7\22\1\310\23\22\2\0\1\22\34\0\7\22"+
    "\1\311\23\22\2\0\1\22\34\0\1\22\1\312\31\22"+
    "\2\0\1\22\34\0\13\22\1\313\17\22\2\0\1\22"+
    "\34\0\6\22\1\314\24\22\2\0\1\22\34\0\5\22"+
    "\1\315\25\22\2\0\1\22\34\0\13\22\1\316\17\22"+
    "\2\0\1\22\34\0\15\22\1\317\15\22\2\0\1\22"+
    "\34\0\14\22\1\320\4\22\1\321\11\22\2\0\1\22"+
    "\34\0\12\22\1\322\20\22\2\0\1\22\34\0\10\22"+
    "\1\323\22\22\2\0\1\22\34\0\15\22\1\324\15\22"+
    "\2\0\1\22\34\0\6\22\1\325\24\22\2\0\1\22"+
    "\34\0\6\22\1\326\24\22\2\0\1\22\34\0\23\22"+
    "\1\327\7\22\2\0\1\22\34\0\1\22\1\330\31\22"+
    "\2\0\1\22\34\0\3\22\1\331\27\22\2\0\1\22"+
    "\34\0\6\22\1\332\24\22\2\0\1\22\34\0\2\22"+
    "\1\333\30\22\2\0\1\22\34\0\6\22\1\334\24\22"+
    "\2\0\1\22\34\0\5\22\1\335\25\22\2\0\1\22"+
    "\34\0\10\22\1\336\22\22\2\0\1\22\34\0\5\22"+
    "\1\337\25\22\2\0\1\22\34\0\24\22\1\340\6\22"+
    "\2\0\1\22\34\0\23\22\1\341\7\22\2\0\1\22"+
    "\34\0\6\22\1\342\24\22\2\0\1\22\34\0\12\22"+
    "\1\343\20\22\2\0\1\22\34\0\12\22\1\344\20\22"+
    "\2\0\1\22\34\0\11\22\1\345\21\22\2\0\1\22"+
    "\34\0\5\22\1\346\2\22\1\347\22\22\2\0\1\22"+
    "\34\0\4\22\1\350\26\22\2\0\1\22\34\0\13\22"+
    "\1\351\17\22\2\0\1\22\34\0\1\352\32\22\2\0"+
    "\1\22\34\0\15\22\1\353\15\22\2\0\1\22\34\0"+
    "\2\22\1\354\30\22\2\0\1\22\34\0\6\22\1\355"+
    "\24\22\2\0\1\22\34\0\20\22\1\356\12\22\2\0"+
    "\1\22\34\0\12\22\1\357\20\22\2\0\1\22\34\0"+
    "\10\22\1\360\22\22\2\0\1\22\34\0\12\22\1\361"+
    "\20\22\2\0\1\22\34\0\15\22\1\362\15\22\2\0"+
    "\1\22\31\0\45\160\1\363\1\267\23\160\3\0\4\22"+
    "\1\364\26\22\2\0\1\22\34\0\6\22\1\365\24\22"+
    "\2\0\1\22\34\0\10\22\1\366\22\22\2\0\1\22"+
    "\34\0\5\22\1\367\25\22\2\0\1\22\34\0\4\22"+
    "\1\370\26\22\2\0\1\22\34\0\2\22\1\371\30\22"+
    "\2\0\1\22\34\0\12\22\1\372\20\22\2\0\1\22"+
    "\34\0\1\22\1\373\31\22\2\0\1\22\34\0\2\22"+
    "\1\374\30\22\2\0\1\22\34\0\6\22\1\375\24\22"+
    "\2\0\1\22\34\0\6\22\1\376\24\22\2\0\1\22"+
    "\34\0\16\22\1\377\14\22\2\0\1\22\34\0\5\22"+
    "\1\u0100\25\22\2\0\1\22\34\0\3\22\1\u0101\27\22"+
    "\2\0\1\22\34\0\2\22\1\u0102\30\22\2\0\1\22"+
    "\34\0\1\22\1\u0103\31\22\2\0\1\22\34\0\2\22"+
    "\1\u0104\30\22\2\0\1\22\34\0\1\22\1\u0105\31\22"+
    "\2\0\1\22\34\0\10\22\1\u0106\22\22\2\0\1\22"+
    "\34\0\7\22\1\u0107\23\22\2\0\1\22\34\0\10\22"+
    "\1\u0108\22\22\2\0\1\22\34\0\24\22\1\u0109\6\22"+
    "\2\0\1\22\34\0\3\22\1\u010a\27\22\2\0\1\22"+
    "\34\0\6\22\1\u010b\24\22\2\0\1\22\34\0\2\22"+
    "\1\u010c\30\22\2\0\1\22\34\0\12\22\1\u010d\20\22"+
    "\2\0\1\22\34\0\22\22\1\u010e\10\22\2\0\1\22"+
    "\34\0\2\22\1\u010f\30\22\2\0\1\22\34\0\2\22"+
    "\1\u0110\30\22\2\0\1\22\34\0\15\22\1\u0111\15\22"+
    "\2\0\1\22\34\0\5\22\1\u0112\25\22\2\0\1\22"+
    "\34\0\14\22\1\u0113\16\22\2\0\1\22\34\0\2\22"+
    "\1\u0114\30\22\2\0\1\22\34\0\6\22\1\u0115\24\22"+
    "\2\0\1\22\34\0\6\22\1\u0116\24\22\2\0\1\22"+
    "\34\0\11\22\1\u0117\21\22\2\0\1\22\34\0\6\22"+
    "\1\u0118\24\22\2\0\1\22\34\0\1\22\1\u0119\31\22"+
    "\2\0\1\22\34\0\12\22\1\u011a\20\22\2\0\1\22"+
    "\34\0\14\22\1\u011b\16\22\2\0\1\22\34\0\10\22"+
    "\1\u011c\22\22\2\0\1\22\34\0\11\22\1\u011d\21\22"+
    "\2\0\1\22\34\0\11\22\1\u011e\21\22\2\0\1\22"+
    "\34\0\2\22\1\u011f\30\22\2\0\1\22\34\0\14\22"+
    "\1\u0120\16\22\2\0\1\22\34\0\6\22\1\u0121\24\22"+
    "\2\0\1\22\34\0\2\22\1\u0122\30\22\2\0\1\22"+
    "\34\0\12\22\1\u0123\20\22\2\0\1\22\34\0\5\22"+
    "\1\u0124\25\22\2\0\1\22\34\0\5\22\1\u0125\25\22"+
    "\2\0\1\22\34\0\5\22\1\u0126\25\22\2\0\1\22"+
    "\34\0\6\22\1\u0127\24\22\2\0\1\22\34\0\10\22"+
    "\1\u0128\22\22\2\0\1\22\34\0\6\22\1\u0129\24\22"+
    "\2\0\1\22\34\0\12\22\1\u012a\20\22\2\0\1\22"+
    "\34\0\3\22\1\u012b\27\22\2\0\1\22\34\0\13\22"+
    "\1\u012c\17\22\2\0\1\22\34\0\12\22\1\u012d\20\22"+
    "\2\0\1\22\34\0\6\22\1\u012e\24\22\2\0\1\22"+
    "\34\0\11\22\1\u012f\21\22\2\0\1\22\34\0\4\22"+
    "\1\u0130\26\22\2\0\1\22\34\0\10\22\1\u0131\22\22"+
    "\2\0\1\22\34\0\6\22\1\u0132\24\22\2\0\1\22"+
    "\34\0\10\22\1\u0133\22\22\2\0\1\22\34\0\13\22"+
    "\1\u0134\17\22\2\0\1\22\34\0\6\22\1\u0135\24\22"+
    "\2\0\1\22\34\0\6\22\1\u0136\24\22\2\0\1\22"+
    "\34\0\10\22\1\u0137\22\22\2\0\1\22\34\0\2\22"+
    "\1\u0138\30\22\2\0\1\22\34\0\5\22\1\u0139\25\22"+
    "\2\0\1\22\34\0\3\22\1\u013a\27\22\2\0\1\22"+
    "\34\0\15\22\1\u013b\15\22\2\0\1\22\34\0\11\22"+
    "\1\u013c\21\22\2\0\1\22\34\0\12\22\1\u013d\20\22"+
    "\2\0\1\22\34\0\5\22\1\u013e\25\22\2\0\1\22"+
    "\34\0\10\22\1\u013f\22\22\2\0\1\22\34\0\1\22"+
    "\1\u0140\31\22\2\0\1\22\34\0\13\22\1\u0141\17\22"+
    "\2\0\1\22\34\0\14\22\1\u0142\16\22\2\0\1\22"+
    "\34\0\2\22\1\u0143\30\22\2\0\1\22\34\0\10\22"+
    "\1\u0144\22\22\2\0\1\22\34\0\11\22\1\u0145\21\22"+
    "\2\0\1\22\34\0\3\22\1\u0146\27\22\2\0\1\22"+
    "\34\0\13\22\1\u0147\17\22\2\0\1\22\34\0\1\22"+
    "\1\u0148\31\22\2\0\1\22\34\0\6\22\1\u0149\24\22"+
    "\2\0\1\22\34\0\4\22\1\u014a\26\22\2\0\1\22"+
    "\34\0\6\22\1\u014b\24\22\2\0\1\22\34\0\12\22"+
    "\1\u014c\20\22\2\0\1\22\34\0\10\22\1\u014d\22\22"+
    "\2\0\1\22\34\0\2\22\1\u014e\30\22\2\0\1\22"+
    "\34\0\13\22\1\u014f\17\22\2\0\1\22\34\0\12\22"+
    "\1\u0150\20\22\2\0\1\22\34\0\10\22\1\u0151\22\22"+
    "\2\0\1\22\34\0\12\22\1\u0152\20\22\2\0\1\22"+
    "\34\0\2\22\1\u0153\30\22\2\0\1\22\34\0\2\22"+
    "\1\u0154\30\22\2\0\1\22\34\0\15\22\1\u0155\15\22"+
    "\2\0\1\22\34\0\5\22\1\u0156\25\22\2\0\1\22"+
    "\34\0\3\22\1\u0157\27\22\2\0\1\22\34\0\24\22"+
    "\1\u0158\6\22\2\0\1\22\34\0\6\22\1\u0159\24\22"+
    "\2\0\1\22\34\0\10\22\1\u015a\22\22\2\0\1\22"+
    "\34\0\13\22\1\u015b\17\22\2\0\1\22\34\0\10\22"+
    "\1\u015c\22\22\2\0\1\22\34\0\23\22\1\u015d\7\22"+
    "\2\0\1\22\34\0\1\u015e\32\22\2\0\1\22\34\0"+
    "\13\22\1\u015f\17\22\2\0\1\22\34\0\2\22\1\u0160"+
    "\30\22\2\0\1\22\34\0\4\22\1\u0161\26\22\2\0"+
    "\1\22\34\0\24\22\1\u0162\6\22\2\0\1\22\34\0"+
    "\1\22\1\u0163\31\22\2\0\1\22\34\0\12\22\1\u0164"+
    "\20\22\2\0\1\22\34\0\2\22\1\u0165\30\22\2\0"+
    "\1\22\34\0\12\22\1\u0166\20\22\2\0\1\22\34\0"+
    "\2\22\1\u0167\30\22\2\0\1\22\34\0\10\22\1\u0168"+
    "\22\22\2\0\1\22\34\0\23\22\1\u0169\7\22\2\0"+
    "\1\22\34\0\23\22\1\u016a\7\22\2\0\1\22\34\0"+
    "\4\22\1\u016b\26\22\2\0\1\22\34\0\1\22\1\u016c"+
    "\31\22\2\0\1\22\34\0\1\22\1\u016d\31\22\2\0"+
    "\1\22\34\0\2\22\1\u016e\30\22\2\0\1\22\34\0"+
    "\2\22\1\u016f\30\22\2\0\1\22\34\0\14\22\1\u0170"+
    "\16\22\2\0\1\22\34\0\4\22\1\u0171\26\22\2\0"+
    "\1\22\34\0\5\22\1\u0172\25\22\2\0\1\22\34\0"+
    "\13\22\1\u0173\17\22\2\0\1\22\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[16008];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\37\1\11\11\4\1\3\11\1\1\2\11"+
    "\62\1\2\0\1\11\1\0\1\11\3\0\1\1\1\0"+
    "\6\11\77\1\1\11\1\0\274\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[371];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _CypherLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _CypherLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 190) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 104: 
          { return K_PROFILE;
          }
        case 116: break;
        case 101: 
          { return K_EXTRACT;
          }
        case 117: break;
        case 51: 
          { return K_XOR;
          }
        case 118: break;
        case 19: 
          { return OP_LESSTHEN;
          }
        case 119: break;
        case 20: 
          { return OP_GREATHERTHEN;
          }
        case 120: break;
        case 28: 
          { return K_IN;
          }
        case 121: break;
        case 89: 
          { return K_REMOVE;
          }
        case 122: break;
        case 109: 
          { return K_ASCENDING;
          }
        case 123: break;
        case 82: 
          { return K_FALSE;
          }
        case 124: break;
        case 4: 
          { return L_INTEGER;
          }
        case 125: break;
        case 14: 
          { return BRACKET_CURLYCLOSE;
          }
        case 126: break;
        case 35: 
          { return LINECOMMENT;
          }
        case 127: break;
        case 25: 
          { return OP_MODULO;
          }
        case 128: break;
        case 7: 
          { return OP_DOT;
          }
        case 129: break;
        case 107: 
          { return K_OPTIONAL;
          }
        case 130: break;
        case 68: 
          { return K_WHEN;
          }
        case 131: break;
        case 67: 
          { return K_LOAD;
          }
        case 132: break;
        case 112: 
          { return K_RELATIONSHIP;
          }
        case 133: break;
        case 72: 
          { return BLOCKCOMMENT;
          }
        case 134: break;
        case 47: 
          { return K_REL;
          }
        case 135: break;
        case 114: 
          { return K_FIELDTERMINATOR;
          }
        case 136: break;
        case 61: 
          { return K_NONE;
          }
        case 137: break;
        case 113: 
          { return K_SHORTESTPATH;
          }
        case 138: break;
        case 103: 
          { return K_FOREACH;
          }
        case 139: break;
        case 87: 
          { return K_COMMIT;
          }
        case 140: break;
        case 30: 
          { return K_OR;
          }
        case 141: break;
        case 115: 
          { return K_ALLSHORTESTPATHS;
          }
        case 142: break;
        case 110: 
          { return K_CONSTRAINT;
          }
        case 143: break;
        case 52: 
          { return L_DECIMAL;
          }
        case 144: break;
        case 100: 
          { return K_HEADERS;
          }
        case 145: break;
        case 77: 
          { return K_INDEX;
          }
        case 146: break;
        case 29: 
          { return K_IS;
          }
        case 147: break;
        case 5: 
          { return OP_BACTICK;
          }
        case 148: break;
        case 81: 
          { return K_WHERE;
          }
        case 149: break;
        case 60: 
          { return K_NULL;
          }
        case 150: break;
        case 16: 
          { return BRACKET_SQUARECLOSE;
          }
        case 151: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 152: break;
        case 102: 
          { return K_EXPLAIN;
          }
        case 153: break;
        case 10: 
          { return SEMICOLON;
          }
        case 154: break;
        case 94: 
          { return K_UNWIND;
          }
        case 155: break;
        case 63: 
          { return K_DROP;
          }
        case 156: break;
        case 6: 
          { return OP_MINUS;
          }
        case 157: break;
        case 33: 
          { return OP_RANGE;
          }
        case 158: break;
        case 43: 
          { return K_ANY;
          }
        case 159: break;
        case 21: 
          { return OP_PLUS;
          }
        case 160: break;
        case 38: 
          { return OP_INVALIDNOTEQUALS;
          }
        case 161: break;
        case 73: 
          { return K_MATCH;
          }
        case 162: break;
        case 79: 
          { return K_ORDER;
          }
        case 163: break;
        case 106: 
          { return K_DISTINCT;
          }
        case 164: break;
        case 83: 
          { return K_BEGIN;
          }
        case 165: break;
        case 80: 
          { return K_LIMIT;
          }
        case 166: break;
        case 97: 
          { return K_STARTS;
          }
        case 167: break;
        case 70: 
          { return K_FROM;
          }
        case 168: break;
        case 49: 
          { return K_NOT;
          }
        case 169: break;
        case 9: 
          { return OP_MUL;
          }
        case 170: break;
        case 98: 
          { return K_SINGLE;
          }
        case 171: break;
        case 32: 
          { return K_BY;
          }
        case 172: break;
        case 27: 
          { return K_AS;
          }
        case 173: break;
        case 62: 
          { return K_NODE;
          }
        case 174: break;
        case 91: 
          { return K_REDUCE;
          }
        case 175: break;
        case 45: 
          { return K_ALL;
          }
        case 176: break;
        case 66: 
          { return K_SKIP;
          }
        case 177: break;
        case 41: 
          { return OP_NOTEQUALS;
          }
        case 178: break;
        case 18: 
          { return OP_EQUAL;
          }
        case 179: break;
        case 88: 
          { return K_CYPHER;
          }
        case 180: break;
        case 15: 
          { return BRACKET_SQUAREOPEN;
          }
        case 181: break;
        case 12: 
          { return PARENTHESE_CLOSE;
          }
        case 182: break;
        case 90: 
          { return K_RETURN;
          }
        case 183: break;
        case 75: 
          { return K_UNION;
          }
        case 184: break;
        case 96: 
          { return K_DELETE;
          }
        case 185: break;
        case 99: 
          { return K_FILTER;
          }
        case 186: break;
        case 17: 
          { return OP_COLON;
          }
        case 187: break;
        case 85: 
          { return K_ASSERT;
          }
        case 188: break;
        case 34: 
          { return L_STRING;
          }
        case 189: break;
        case 11: 
          { return PARENTHESE_OPEN;
          }
        case 190: break;
        case 71: 
          { return K_JOIN;
          }
        case 191: break;
        case 23: 
          { return OP_QUESTIONSIGN;
          }
        case 192: break;
        case 53: 
          { return L_IDENTIFIER_TEXT;
          }
        case 193: break;
        case 59: 
          { return K_ELSE;
          }
        case 194: break;
        case 69: 
          { return K_WITH;
          }
        case 195: break;
        case 54: 
          { return K_THEN;
          }
        case 196: break;
        case 46: 
          { return K_CSV;
          }
        case 197: break;
        case 24: 
          { return OP_PIPE;
          }
        case 198: break;
        case 56: 
          { return K_CASE;
          }
        case 199: break;
        case 84: 
          { return K_YIELD;
          }
        case 200: break;
        case 42: 
          { return K_AND;
          }
        case 201: break;
        case 44: 
          { return K_ASC;
          }
        case 202: break;
        case 40: 
          { return OP_PLUSEQUALS;
          }
        case 203: break;
        case 111: 
          { return K_DESCENDING;
          }
        case 204: break;
        case 22: 
          { return OP_COMMA;
          }
        case 205: break;
        case 76: 
          { return K_USING;
          }
        case 206: break;
        case 93: 
          { return K_UNIQUE;
          }
        case 207: break;
        case 3: 
          { return L_IDENTIFIER;
          }
        case 208: break;
        case 108: 
          { return K_PERIODIC;
          }
        case 209: break;
        case 57: 
          { return K_CALL;
          }
        case 210: break;
        case 13: 
          { return BRACKET_CURLYOPEN;
          }
        case 211: break;
        case 78: 
          { return K_START;
          }
        case 212: break;
        case 48: 
          { return K_END;
          }
        case 213: break;
        case 31: 
          { return K_ON;
          }
        case 214: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 215: break;
        case 65: 
          { return K_SCAN;
          }
        case 216: break;
        case 39: 
          { return OP_GREATERTHANEQUALS;
          }
        case 217: break;
        case 105: 
          { return K_CONTAINS;
          }
        case 218: break;
        case 58: 
          { return K_ENDS;
          }
        case 219: break;
        case 50: 
          { return K_SET;
          }
        case 220: break;
        case 55: 
          { return K_TRUE;
          }
        case 221: break;
        case 37: 
          { return OP_LESSTHANEQUALS;
          }
        case 222: break;
        case 74: 
          { return K_MERGE;
          }
        case 223: break;
        case 26: 
          { return OP_POW;
          }
        case 224: break;
        case 86: 
          { return K_CREATE;
          }
        case 225: break;
        case 92: 
          { return K_EXISTS;
          }
        case 226: break;
        case 8: 
          { return OP_DIVIDE;
          }
        case 227: break;
        case 36: 
          { return OP_REGEXMATCH;
          }
        case 228: break;
        case 64: 
          { return K_DESC;
          }
        case 229: break;
        case 95: 
          { return K_DETACH;
          }
        case 230: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
